ALTER TABLE bot_users
    ADD COLUMN IF NOT EXISTS billing_plan VARCHAR(16) NOT NULL DEFAULT 'free',
    ADD COLUMN IF NOT EXISTS usage_period VARCHAR(7) NOT NULL DEFAULT to_char(CURRENT_DATE, 'YYYY-MM'),
    ADD COLUMN IF NOT EXISTS period_tokens_used INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS period_messages INTEGER NOT NULL DEFAULT 0;
